// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYE6iPDPRD5U0SHtdIK8VIj6pIr4BtHM4',
    appId: '1:134063295991:web:0e28cedbfdb883f9fb72f2',
    messagingSenderId: '134063295991',
    projectId: 'flutterfire-ui-codelab-75b20',
    authDomain: 'flutterfire-ui-codelab-75b20.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-75b20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN9n-NeYl9il0hua7Hl6b2sYYgxpKKkwY',
    appId: '1:134063295991:android:808e037b53dc20f8fb72f2',
    messagingSenderId: '134063295991',
    projectId: 'flutterfire-ui-codelab-75b20',
    storageBucket: 'flutterfire-ui-codelab-75b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtrij5uISJfvOLXMHUSCZaM0x1R-wjGgI',
    appId: '1:134063295991:ios:22be6d68cf073e3cfb72f2',
    messagingSenderId: '134063295991',
    projectId: 'flutterfire-ui-codelab-75b20',
    storageBucket: 'flutterfire-ui-codelab-75b20.appspot.com',
    iosClientId: '134063295991-s0pbf5g13qp4lc6c5gg7rjhecbblndb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtrij5uISJfvOLXMHUSCZaM0x1R-wjGgI',
    appId: '1:134063295991:ios:a1fe1170310b28d7fb72f2',
    messagingSenderId: '134063295991',
    projectId: 'flutterfire-ui-codelab-75b20',
    storageBucket: 'flutterfire-ui-codelab-75b20.appspot.com',
    iosClientId: '134063295991-2qhip54143vud6mgd4kvdd1nm8cffkei.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
