name: complete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.12.0
  firebase_ui_oauth_google: 1.2.17
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  import_sorter: ^4.6.0 # Verifica por  versiones más recientes

flutter:
  uses-material-design: true
  assets:
    - assets/flutterfire_300x.png 